# Generated by Django 3.1.4 on 2020-12-16 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201216_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('d998f346-ad59-4a95-a3e4-ded71765e14f')),
        ),
        migrations.AlterField(
            model_name='store',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('ca8e8308-f1ef-46a4-82a5-c9343b7211d0')),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('f1e73739-1611-4ca6-9d3a-2c76c477401d')),
        ),
        migrations.CreateModel(
            name='SignUpVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.UUID('2c17831c-344d-461f-99d6-a044cab44c26'))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
