# Generated by Django 3.1.4 on 2020-12-17 08:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201216_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=1, upload_to='images/%d%m/%y'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('dd72bd45-01b5-4053-b83d-d4a648795436')),
        ),
        migrations.AlterField(
            model_name='signupverification',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('1c2c56a9-a3a2-4afb-b08b-c0b1b5fdd0f3')),
        ),
        migrations.AlterField(
            model_name='store',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('0fc53cde-db99-479f-b69e-e431ee64918e')),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('bd8a2a6d-409d-4067-8449-6b34e5e91053')),
        ),
    ]
