# Generated by Django 3.1.4 on 2020-12-17 09:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20201217_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('61e5e367-512d-490e-9412-59114fa05a4d')),
        ),
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.ImageField(upload_to='flags'),
        ),
        migrations.AlterField(
            model_name='signupverification',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('4a576a74-68f8-42f1-8722-b38e7b2b53a9')),
        ),
        migrations.AlterField(
            model_name='store',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('c503b8e7-f6fa-49ea-b799-9964ac2e04dd')),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('47653371-80c5-4275-a1b1-6125de541b05')),
        ),
    ]
