# Generated by Django 3.1.4 on 2020-12-17 09:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20201217_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('b5bad7dd-def6-4060-a37d-a2722e1d2d02')),
        ),
        migrations.AlterField(
            model_name='signupverification',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('7f584659-9ce3-44bc-9aba-458499118b05')),
        ),
        migrations.AlterField(
            model_name='store',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('7259b6c3-798d-4dcc-9cd5-e8ef3e953f53')),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('e6c06adc-4712-4c37-b1b2-78658efd6109')),
        ),
    ]
