# Generated by Django 3.1.4 on 2020-12-18 06:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20201217_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allowed_clients',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allowed_countries',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allowed_stores',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='client',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('b9f2eecf-72fd-49f5-9665-b79a23eb237d')),
        ),
        migrations.AlterField(
            model_name='signupverification',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('cc81aeaa-76f8-4c25-9d1c-ee1f19fccac2')),
        ),
        migrations.AlterField(
            model_name='store',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('3d11dc21-9b14-4773-a8c0-4342828df724')),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('e039b733-9ab1-4721-bcc8-ec6d0fbae3aa')),
        ),
    ]
