# Generated by Django 3.1.4 on 2020-12-18 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20201218_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('7cafe651-83a6-48e5-a65e-d99f031fa4d6')),
        ),
        migrations.AlterField(
            model_name='image',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_image', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='signupverification',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('5c89d4cf-0616-4009-9945-b7f8046e5672')),
        ),
        migrations.AlterField(
            model_name='store',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('93384031-fb0c-4356-b629-9cdd28d659f6')),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('4629f1d4-a4e8-480e-b2e5-e6804197c736')),
        ),
    ]
